In [2]:
import torch
import torch.nn.functional as F

In [3]:
# Outputs
predictions = torch.log(torch.rand(3))
predictions

tensor([-2.1817, -0.8039, -0.2479])

In [6]:
# Softmax
F.softmax(predictions, dim=-1)

tensor([0.0842, 0.3338, 0.5820])

In [7]:
# Low temperature
F.softmax(predictions / 0.5, dim=-1)

tensor([0.0155, 0.2437, 0.7408])

In [8]:
# High temperature
F.softmax(predictions / 5, dim=-1)

tensor([0.2639, 0.3476, 0.3885])

In [9]:
# Almost uniform distribution
F.softmax(predictions / 100, dim=-1)

tensor([0.3297, 0.3342, 0.3361])