In [1]:
import torch
import torch.nn as nn # модуль для нейросетей

In [2]:
# выводим 5 переменных для 4 экземпляров
prediction = torch.randn(4, 5)

In [3]:
# реальные значения
label = torch.randn(4, 5)

In [4]:
# определяем функцию потерб
# reduction - то, как устреднять ошибку по батчам
mse = torch.nn.MSELoss(reduction='none')

In [5]:
# считаем MSE
loss = mse(prediction, label)

In [6]:
loss

tensor([[2.1329e+00, 1.9783e+00, 1.4494e+00, 6.2196e-01, 1.0288e+01],
        [1.1829e+00, 6.2260e-02, 4.7519e+00, 2.5211e-01, 4.0963e+00],
        [1.0701e-01, 3.6831e+00, 8.8405e-01, 7.2010e+00, 1.9750e+00],
        [5.5717e-01, 6.1720e-03, 1.7789e+00, 5.3779e-01, 1.4056e+00]])

In [7]:
mse = torch.nn.MSELoss(reduction='mean')
loss = mse(prediction, label)
loss

tensor(2.2476)

In [8]:
# математическая формула
((prediction - label) ** 2).mean()

tensor(2.2476)

Бинарная кросс энтропия

In [9]:
prediction

tensor([[-1.2843, -0.1106,  0.6590,  0.4175,  2.1257],
        [-2.1595,  0.2726,  1.1492,  0.8342,  0.3376],
        [ 0.4687, -1.7771,  2.1319, -1.3713, -1.6372],
        [ 0.2354, -1.1714,  0.7720,  1.1171, -0.5191]])

In [10]:
# сделали массив label нулями, а потом заплнили его ослучайными числами из [0, 1]
label = torch.zeros(4, 5).random_(0, 1+1)

In [11]:
label

tensor([[1., 1., 1., 0., 1.],
        [1., 0., 0., 1., 0.],
        [0., 1., 0., 0., 1.],
        [1., 0., 0., 0., 1.]])

In [12]:
# сигмоида нужна, чтобы привести prediction к 0, 1
sigmoid = nn.Sigmoid()

In [13]:
# определяем функию потерь
bce = nn.BCELoss(reduction='mean')

In [14]:
bce(sigmoid(prediction), label)

tensor(1.0532)

In [15]:
# попробуем bce с сигмоидой
bces = torch.nn.BCEWithLogitsLoss(reduction='mean')

In [16]:
bces(prediction, label)

tensor(1.0532)

Реализация на python

In [17]:
import numpy as np

In [18]:
# конвертируем
x = prediction.numpy()
y = label.numpy()

In [19]:
# приводим к [0, 1]
def my_sigmoid(x):
    return 1 / (1 + np.exp(-x))
x = my_sigmoid(x)
x

array([[0.21682414, 0.4723774 , 0.6590257 , 0.60289246, 0.893378  ],
       [0.10344338, 0.5677339 , 0.7593715 , 0.6972358 , 0.5836001 ],
       [0.6150805 , 0.14465943, 0.89396423, 0.20241147, 0.16284607],
       [0.5585877 , 0.23660557, 0.683946  , 0.75344926, 0.3730512 ]],
      dtype=float32)

In [20]:
# считаем
loss_values = []
for i in range(len(y)):
    batch_loss = []
    for j in range(len(y[0])):
        batch_loss.append((-np.log(x[i][j])) if y[i][j] == 1 else (-np.log(1 - x[i][j])))
    loss_values.append(batch_loss)
np.mean(loss_values)

np.float32(1.0532098)