In [1]:
import torch
import torch.nn as nn

In [2]:
# создаём слой
layer = nn.Linear(5, 5)

In [3]:
# начальные веса
layer.weight.data

tensor([[ 0.1292, -0.3593,  0.2844,  0.2285, -0.1197],
        [ 0.4386, -0.1842, -0.3360,  0.3950, -0.3111],
        [-0.3172, -0.4263,  0.2601, -0.4052,  0.0157],
        [-0.0872,  0.0506,  0.1767, -0.0965, -0.4052],
        [-0.1609, -0.3535, -0.2070, -0.1642, -0.2684]])

In [4]:
# равномерное распределение
nn.init.uniform_(layer.weight, a=0, b=3)

Parameter containing:
tensor([[2.2545, 1.4513, 1.6913, 2.0390, 0.9515],
        [0.0692, 1.4974, 2.6600, 1.1512, 1.1854],
        [1.5054, 0.7855, 2.8659, 1.3305, 1.6490],
        [2.9281, 2.8612, 0.9255, 2.8492, 1.5177],
        [2.1801, 0.1405, 0.8243, 2.1693, 0.4627]], requires_grad=True)

In [5]:
# номральное распределение
nn.init.normal_(layer.weight, mean=0, std=1)

Parameter containing:
tensor([[-0.5266, -3.0534,  0.8280, -0.5370,  0.6563],
        [ 0.4364, -1.4379,  0.2479,  0.2919, -1.2764],
        [ 0.7568,  0.9964,  0.4187, -1.5426, -1.4094],
        [ 0.3048, -0.4186, -0.0603,  0.7294, -0.6310],
        [-2.6540,  0.9964, -1.8558, -0.0210,  0.8548]], requires_grad=True)

In [6]:
# можно константой, но очень нежелательно в большей части случаев
# можно, например, для инициализации смещения
nn.init.constant_(layer.bias, val=2)
# или аналоги для 0 и 1
# nn.init.zeros_(layer.bias)
# nn.init.ones_(layer.bias)

Parameter containing:
tensor([2., 2., 2., 2., 2.], requires_grad=True)

In [7]:
# инициализация Xavier
nn.init.xavier_normal_(layer.weight, gain=1)

Parameter containing:
tensor([[-0.8848, -0.0292, -0.0781,  0.6930, -0.6971],
        [-0.1057,  0.0654,  0.0226, -0.3032,  0.2828],
        [ 0.6480, -0.0857,  0.6977,  0.1187, -0.7740],
        [ 0.4626, -0.3328,  0.2699,  0.5803, -0.3436],
        [-0.1792,  0.4141,  0.2458, -0.2379, -0.8754]], requires_grad=True)