In [1]:
import torch

In [2]:
# тензр - вектор
a = torch.tensor([2, 2, 1])
print(a)

tensor([2, 2, 1])


In [3]:
# тензор матрица
b = torch.tensor([[2, 1, 4], [3, 5, 4], [1, 2, 0], [4, 3, 2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [4]:
# shape и size() - одно и то же
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [5]:
print(b.shape[0])

4


In [6]:
# тензор float
c = torch.FloatTensor([[2, 1, 4], [3, 5, 4], [1, 2, 0], [4, 3, 2]])
# c = torch.tensor([[2, 1, 4], [3, 5, 4], [1, 2, 0], [4, 3, 2]], dtype=torch.float)

In [7]:
# тензор double
d = torch.DoubleTensor([[2, 1, 4], [3, 5, 4], [1, 2, 0], [4, 3, 2]])
# d = torch.tensor([[2, 1, 4], [3, 5, 4], [1, 2, 0], [4, 3, 2]], dtype=torch.double)

In [8]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [9]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [10]:
# среднее
print(c.mean())

tensor(2.5833)


In [11]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [12]:
# стандартное отклонение
print(c.std())

tensor(1.5050)


In [13]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [14]:
# Используем view, чтобы изменить размерность тензора
# Можно испоьзовать -1, чтобы второй размер был подобран автоматически
print(b.view(-1, 1))
print(b.view(12))
print(b.view(-1, 4))
print(b.view(3, 4))
print(b.view(2, 2, 3))
print('\n')
b = b.view(1, -1)
print(b)
print(b.shape)
print('\n')
d3_tensor = torch.randn(2, 3, 4) # (channels, rows, columns)
print(d3_tensor)
print(d3_tensor.view(2, 12))
print(d3_tensor.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[[2, 1, 4],
         [3, 5, 4]],

        [[1, 2, 0],
         [4, 3, 2]]])


tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])


tensor([[[-0.4616, -1.5302,  1.2495,  0.5920],
         [ 0.1602, -0.7592,  0.6504,  0.7004],
         [-0.1747,  0.4352,  0.1591,  0.4481]],

        [[-0.3404,  0.0116, -0.5371, -0.3592],
         [ 0.2802,  2.7261,  0.3369, -0.4905],
         [-0.0462,  2.2608, -1.9153,  1.2462]]])
tensor([[-0.4616, -1.5302,  1.2495,  0.5920,  0.1602, -0.7592,  0.6504,  0.7004,
         -0.1747,  0.4352,  0.1591,  0.4481],
        [-0.3404,  0.0116, -0.5371, -0.3592,  0.2802,  2.7261,  0.3369, -0.4905,
         -0.046

In [15]:
# случайные числа от 0 до 1
r1 = torch.rand(4, 4)
print(r1)

tensor([[0.4701, 0.0720, 0.3567, 0.9527],
        [0.4053, 0.8729, 0.5728, 0.3306],
        [0.8584, 0.0552, 0.0493, 0.1052],
        [0.5202, 0.9773, 0.2448, 0.1658]])


In [16]:
# случайные числа из нормального распределения
r2 = torch.randn(4, 4)
print(r2)

tensor([[-0.1610, -1.3663,  1.3724,  0.1734],
        [ 0.6061, -0.1438,  0.0769, -0.1681],
        [ 0.1356, -0.1145, -0.6760, -1.5703],
        [-0.9065, -1.1904, -0.6396,  0.2671]])


In [17]:
# случайные целый от 6 до 9 в виде тензора размером [3, 3]
r3 = torch.randint(6, 9+1, (3, 3))
print(r3)
print(r3.dtype)

tensor([[6, 6, 8],
        [9, 7, 8],
        [7, 9, 6]])
torch.int64


In [18]:
# количесвто элементов в тензоре
print(torch.numel(r3))

9


In [19]:
# тензор [3, 3] нулей типа long
z = torch.zeros(3, 3, dtype=torch.long)
print(z)
# тензор [3, 3] единиц
x = torch.ones(3, 3)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [20]:
# тензор случайных чисел размером как у жругого тензора
r2_like = torch.randn_like(r2, dtype=torch.double)
print(r2_like)

tensor([[-0.5899, -0.7807,  2.0536,  0.4804],
        [-2.0948,  0.9879, -0.3652,  0.3333],
        [-1.0041, -0.9312,  0.7326,  0.9957],
        [-2.0434,  0.5601,  0.8661, -0.4166]], dtype=torch.float64)


In [21]:
# можно сложить тензоры с одинаковыми размерами и типами
add_result = torch.add(r1, r2)
print(r1)
print(r2)
print(add_result)

tensor([[0.4701, 0.0720, 0.3567, 0.9527],
        [0.4053, 0.8729, 0.5728, 0.3306],
        [0.8584, 0.0552, 0.0493, 0.1052],
        [0.5202, 0.9773, 0.2448, 0.1658]])
tensor([[-0.1610, -1.3663,  1.3724,  0.1734],
        [ 0.6061, -0.1438,  0.0769, -0.1681],
        [ 0.1356, -0.1145, -0.6760, -1.5703],
        [-0.9065, -1.1904, -0.6396,  0.2671]])
tensor([[ 0.3091, -1.2943,  1.7290,  1.1261],
        [ 1.0114,  0.7290,  0.6497,  0.1625],
        [ 0.9940, -0.0593, -0.6267, -1.4652],
        [-0.3863, -0.2131, -0.3947,  0.4329]])


In [22]:
# аналог +=
# без _ это будет обычное сложение
print(r2)
print(r1)
r2.add_(r1)
print(r2)

tensor([[-0.1610, -1.3663,  1.3724,  0.1734],
        [ 0.6061, -0.1438,  0.0769, -0.1681],
        [ 0.1356, -0.1145, -0.6760, -1.5703],
        [-0.9065, -1.1904, -0.6396,  0.2671]])
tensor([[0.4701, 0.0720, 0.3567, 0.9527],
        [0.4053, 0.8729, 0.5728, 0.3306],
        [0.8584, 0.0552, 0.0493, 0.1052],
        [0.5202, 0.9773, 0.2448, 0.1658]])
tensor([[ 0.3091, -1.2943,  1.7290,  1.1261],
        [ 1.0114,  0.7290,  0.6497,  0.1625],
        [ 0.9940, -0.0593, -0.6267, -1.4652],
        [-0.3863, -0.2131, -0.3947,  0.4329]])


In [23]:
# можно делать все те же операции, что и с numpy array, в том числе и бродкастинг и срезы
# можно не писать add, add_ и тд, а заменять их символами +, += и тд.

In [24]:
# срезы
print(r2)
print(r2[:, 1])
print(r2[:3, :])
print('\n')
# получаем один элемент и значение тензора размером [1, 1]
num_ten = r2[2, 3]
print(num_ten)
print(num_ten.item())

tensor([[ 0.3091, -1.2943,  1.7290,  1.1261],
        [ 1.0114,  0.7290,  0.6497,  0.1625],
        [ 0.9940, -0.0593, -0.6267, -1.4652],
        [-0.3863, -0.2131, -0.3947,  0.4329]])
tensor([-1.2943,  0.7290, -0.0593, -0.2131])
tensor([[ 0.3091, -1.2943,  1.7290,  1.1261],
        [ 1.0114,  0.7290,  0.6497,  0.1625],
        [ 0.9940, -0.0593, -0.6267, -1.4652]])


tensor(-1.4652)
-1.4651790857315063


Связь с numpy

In [25]:
import numpy as np

In [26]:
# конвертация torch -> numpy
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
print('\n')
# как меняется массив при изменении тензора (по ссылке)
a += 1
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
# обратная конвертация
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
print('\n')
# как меняется тензор при изменении массива (по ссылке)
a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
import torch_directml

In [29]:
# переносим на GPU (аналог .cuda())
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    print("Используется NVidia GPU")
elif torch_directml.is_available():
    device = torch_directml.device()
    print("Используется AMD GPU")
else:
    device = torch.device('cpu')
    print("Испоользуется CPU")
r2 = r2.to(device)
print(r2)

Используется AMD GPU
tensor([[ 0.3091, -1.2943,  1.7290,  1.1261],
        [ 1.0114,  0.7290,  0.6497,  0.1625],
        [ 0.9940, -0.0593, -0.6267, -1.4652],
        [-0.3863, -0.2131, -0.3947,  0.4329]], device='privateuseone:0')


In [30]:
# конвертация списка в тензор
a = [2, 3, 4, 1]
print(a)
b = torch.tensor(a)
print(b)

[2, 3, 4, 1]
tensor([2, 3, 4, 1])


In [31]:
a = [[1., 2.], [3., 4.], [5., 6.], [7., 8.]]
b = torch.tensor(a)
print(a)
print(b)

[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0], [7.0, 8.0]]
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


Конкатенация тензоров

In [32]:
# конкатенация тензоров вдоль оси 0
first_1 = torch.randn(2, 5)
print(first_1)
second_1 = torch.randn(3, 5)
print(second_1)
concat_1 = torch.cat([first_1, second_1], 0) # dim=0 default
print(concat_1)
print(concat_1.shape)
print('\n')
# конкатенация тензоров вдоль оси 1
first_2 = torch.randn(2, 3)
print(first_2)
second_2 = torch.randn(2, 5)
print(second_2)
concat_2 = torch.cat([first_2, second_2], 1)
print(concat_2)
print(concat_2.shape)

tensor([[ 0.1193, -0.4474,  0.5321, -0.4948,  1.3261],
        [-2.6362, -0.2274, -2.3478, -0.7162, -0.1145]])
tensor([[ 0.5727, -1.6605, -0.7439,  0.3144, -1.0897],
        [ 0.2963,  0.2211,  0.0873,  0.9825,  1.0238],
        [-0.0800, -0.9764,  1.0853,  0.9715,  0.8327]])
tensor([[ 0.1193, -0.4474,  0.5321, -0.4948,  1.3261],
        [-2.6362, -0.2274, -2.3478, -0.7162, -0.1145],
        [ 0.5727, -1.6605, -0.7439,  0.3144, -1.0897],
        [ 0.2963,  0.2211,  0.0873,  0.9825,  1.0238],
        [-0.0800, -0.9764,  1.0853,  0.9715,  0.8327]])
torch.Size([5, 5])


tensor([[-0.8243,  0.1723,  0.8802],
        [-0.6717,  1.4680, -1.0257]])
tensor([[ 0.9659,  1.1799, -1.0444, -0.0722, -0.1713],
        [-0.0384, -2.1196, -0.4141, -0.7289,  1.6159]])
tensor([[-0.8243,  0.1723,  0.8802,  0.9659,  1.1799, -1.0444, -0.0722, -0.1713],
        [-0.6717,  1.4680, -1.0257, -0.0384, -2.1196, -0.4141, -0.7289,  1.6159]])
torch.Size([2, 8])


In [33]:
# добавляем измерение в тензор
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0) # на какую позицию добавляется новое измерение ([4] -> [1, 4])
print(tensor_a)
print(tensor_a.shape)
print('\n')
tensor_b = torch.unsqueeze(tensor_1, 1)
print(tensor_b)
print(tensor_b.shape)
print('\n')
tensor_2 = torch.rand(2, 3, 4)
tensor_c = tensor_2[:, :, 2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c, 2)
print(tensor_d)
print(tensor_d.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])


tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[0.2907, 0.6654, 0.4039],
        [0.3448, 0.7637, 0.0219]])
torch.Size([2, 3])


tensor([[[0.2907],
         [0.6654],
         [0.4039]],

        [[0.3448],
         [0.7637],
         [0.0219]]])
torch.Size([2, 3, 1])


In [34]:
# можно использовать метод
print(tensor_1.unsqueeze(1))

tensor([[1],
        [2],
        [3],
        [4]])


In [35]:
# После require_grad=True тензор запоминает, как он создаётся и используется
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = torch.tensor([4., 5., 6.], requires_grad=True)
z = x + y
print(z)
print(z.grad_fn)
print('\n')
# Проверяем другую функцию тензора
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)


tensor(21., grad_fn=<SumBackward0>)


In [36]:
# Считаем backprop (производная s - функция потерь по x)
s.backward()
print(x.grad)

tensor([1., 1., 1.])


In [37]:
# requieres_grad по умолчанию false
x = torch.randn(2, 2)
y = torch.randn(2, 2)
print(x.requires_grad, y.requires_grad)
z = x + y
print(z.grad_fn)
print('\n')
# можно изменить этот параметр
x.requires_grad_()
y.requires_grad_()
z = x + y
print(z.grad_fn)
print(z.requires_grad)
print('\n')
# detach возвращает копию, но без истории вычисления
new_z = z.detach()
print(new_z.grad_fn)
print('\n')
# градиент можно временно отключать
print(x.requires_grad)
print((x + 10).requires_grad)
with torch.no_grad():
    print((x + 10).requires_grad)

False False
None


True


None


True
True
False


In [38]:
# пример
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)
z = y * y * 3
out = z.mean()
print(z, out)
out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
