In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as f
import torch.optim as optim

In [2]:
# The indices of the words represent the values in the lookup table
word_to_ind = {'I': 0, 'love': 1, 'eating': 2, 'and': 3, 'sleeping': 4}
embeddings = nn.Embedding(5, 7)
word_index = torch.tensor([word_to_ind['love']])
print(word_index)

tensor([1])


In [3]:
# Get the embeddibg
love = embeddings(word_index)
print(love)
print(love.shape)

tensor([[-0.9599, -0.2227,  1.6666, -0.8327,  1.2426, -0.0639,  0.6175]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([1, 7])


In [5]:
# Get all embeddings
all_ind = torch.tensor([w for w in range(5)], dtype=torch.long)
all_words = embeddings(all_ind)
print(all_ind)
print(all_words)
print(all_words.shape)

tensor([0, 1, 2, 3, 4])
tensor([[ 0.1160, -0.5850,  0.9248,  0.9647, -0.5662,  0.0702,  0.2952],
        [-0.9599, -0.2227,  1.6666, -0.8327,  1.2426, -0.0639,  0.6175],
        [-1.0295,  0.6278,  0.4491, -1.1880,  0.1560, -0.8383,  0.3829],
        [ 0.8733, -0.4214, -0.2931, -1.3312, -0.1626,  1.0915, -0.3970],
        [ 0.2191, -0.8561,  0.6119,  0.1502, -0.2061, -1.4497, -1.9476]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([5, 7])
